version: '3.7'

services:
    phpfpm:
        build:
            context: ./dockerfile/phpfpm
            dockerfile: Dockerfile
        image: magento_test
        container_name: magento_container_php_test
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./source:/var/www/html
            - ./php/ini:/usr/local/etc/php
        networks:
            - magento_test
    app:
        image: nginx:1.16.1
        container_name: magento_container_nginx_test
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./source:/var/www/html
        networks:
            - magento_test
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d:ro
        environment:
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: myuser
            MYSQL_PASSWORD: test123
            MYSQL_ROOT_PASSWORD: test123
        networks:
            - magento_test
networks:
    magento_test:
        driver: bridge